version: '3.9'
services:
  crud-php:
    container_name: '${CONTAINER_NAME_PHP:-crud-php}'
    networks:
      dominion_net:
        ipv4_address: ${DOCKER_IP_ADDRESS_CRUD}
    hostname: crud
    domainname: crud.dd.test
    build:
      context: ./
      dockerfile: docker/${DOCKER_FILE}
    ports:
      - "${PHP_PORT:-80}:80"
    links:
      - crud-mysql
    volumes:
      - ./:/var/www/html
      - ./errors/httpd/:/var/log/httpd
      - ./errors/php/:/var/log/php
      - ./errors/xdebug/:/var/log/xdebug
      - ./errors/freetds/:/var/log/freetds
      - ./errors/odbc/:/var/log/odbc
      - ./errors/xdebug_trace/:/var/log/xdebug_trace
      - ./errors/testtmp/:/testtmp2
#      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
  crud-mysql:
    container_name: '${CONTAINER_NAME_MYSQL:-crud-mysql}'
    build:
      context: ./docker/mysql/8.0
      dockerfile: Dockerfile
    volumes:
      - './docker/mysql/init:/etc/mysql/conf.d'
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/db:/var/lib/mysql
#      - ./docker/mysql/backup:/home/dominion/backup
    networks:
     - dominion_net
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_DATABASE2: 'random'
      MYSQL_DATABASE3: 'emr'
      MYSQL_DATABASE4: 'alert'
      MYSQL_USER: "${MYSQL_DOCKER_DB:-crud}"
      MYSQL_PASSWORD: "${MYSQL_DOCKER_PASSWORD:-crud}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_DOCKER_ROOT_PASSWORD:-crud}"
    ports:
      - "${MYSQL_PORT:-33063}:3306"
    expose:
      - '3306'
  crud-mssql:
    container_name: '${CONTAINER_NAME_MSSQL:-crud-mssql}'
    build:
      context: ./docker/mssql
      dockerfile: Dockerfile
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=${DB_MSSQL_PASSWORD:-PWDpwdPass4}'
    volumes:
      - './docker/mssql/init:/var/opt/mssql/data'
      - './docker/mssql/log:/var/opt/mssql/log'
      - './docker/mssql/secrets:/var/opt/mssql/secrets'
    ports:
      - '${DB_PORT_MSSQL:-1433}:1433'
  crud-proxy:
    container_name: '${CONTAINER_NAME_PROXY:-crud-proxy}'
    image: nginx
    build:
      dockerfile: docker/Dockerfile.Nginx
    networks:
      - dominion_net
    links:
      - crud-php
    ports:
      - 82:80
      - 444:443
      # - 8080:8080
    volumes:
      - ./docker/config/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ssl/crud-dd-test.crt:/etc/nginx/crud-dd-test.crt
      - ./docker/config/ssl/crud-dd-test.key:/etc/nginx/crud-dd-test.key
volumes:
  mysql:
    driver: "local"
networks:
  dominion_net:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_IP_SUBNET}
        - subnet: "2001:3984:3989::/64"
