version: '3.9'
services:
  php:
    container_name: '${CONTAINER_NAME_PHP:-crud-php}'
    networks:
      dominion_net:
        ipv4_address: ${DOCKER_IP_ADDRESS_CRUD}
    hostname: crud
    domainname: crud.test
    build:
      context: ./
      dockerfile: docker/${DOCKER_FILE}
    ports:
      - "${PHP_PORT:-80}:80"
    links:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./errors/httpd/:/var/log/httpd
      - ./errors/php/:/var/log/php
      - ./errors/xdebug/:/var/log/xdebug
      - ./errors/freetds/:/var/log/freetds
      - ./errors/odbc/:/var/log/odbc
      - ./errors/xdebug_trace/:/var/log/xdebug_trace
      - ./errors/testtmp/:/testtmp2
#      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
  mysql:
    container_name: '${CONTAINER_NAME_MYSQL:-crud-mysql}'
    build:
      context: ./docker/mysql/5.7
      dockerfile: Dockerfile
    volumes:
      - './docker/mysql/init:/etc/mysql/conf.d'
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/backup:/home/dominion/backup
    networks:
     - dominion_net
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_DATABASE2: 'random'
      MYSQL_DATABASE3: 'emr'
      MYSQL_DATABASE4: 'alert'
      MYSQL_USER: 'crud'
      MYSQL_PASSWORD: 'crud'
      MYSQL_ROOT_PASSWORD: 'crud'
    ports:
      - "${MYSQL_PORT:-33063}:3306"
    expose:
      - '3306'
  mssql:
    container_name: '${CONTAINER_NAME_MSSQL:-dconnect-mssql}'
    build:
      context: ./docker/mssql
      dockerfile: Dockerfile
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=${DB_MSSQL_PASSWORD:-PWDpwdPass4}'
    volumes:
      - './docker/mssql/init:/var/opt/mssql/data'
      - './docker/mssql/log:/var/opt/mssql/log'
      - './docker/mssql/secrets:/var/opt/mssql/secrets'
    ports:
      - '${DB_PORT_MSSQL:-1433}:1433'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${CONTAINER_NAME_PHPMYADMIN:-crud-phpmyadmin}'
    container_name: crud-phpmyadmin
    networks:
      dominion_net:
        ipv4_address: ${DOCKER_IP_ADDRESS_PHPMYADMIN}
    env_file:
      - docker/phpmyadmin/phpmyadmin.env
    networks:
      - dominion_net
    links:
      - mysql:mysql
    ports:
      - "${PHPMYADMIN_PORT_CRUD:-90}:80"
    volumes:
      - /sessions
      - ./docker/phpmyadmin/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/phpmyadmin/php.ini-production:/usr/local/etc/php/php.ini-production
    environment:
      MYSQL_USER: connect
      MYSQL_PASSWORD: connect
      MYSQL_ROOT_PASSWORD: connect
      PMA_HOST: mysql
volumes:
  mysql:
    driver: "local"
networks:
  dominion_net:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_IP_SUBNET}
        - subnet: "2001:3984:3989::/64"
